#!/bin/sh
set -e
# Automatically added by dh_icons/13.31~bpo13+1
if command -v update-icon-caches >/dev/null; then
	update-icon-caches /usr/share/icons/Yaru /usr/share/icons/Yaru-blue /usr/share/icons/Yaru-blue-dark /usr/share/icons/Yaru-dark /usr/share/icons/Yaru-magenta /usr/share/icons/Yaru-magenta-dark /usr/share/icons/Yaru-olive /usr/share/icons/Yaru-olive-dark /usr/share/icons/Yaru-prussiangreen /usr/share/icons/Yaru-prussiangreen-dark /usr/share/icons/Yaru-purple /usr/share/icons/Yaru-purple-dark /usr/share/icons/Yaru-red /usr/share/icons/Yaru-red-dark /usr/share/icons/Yaru-sage /usr/share/icons/Yaru-sage-dark /usr/share/icons/Yaru-wartybrown /usr/share/icons/Yaru-wartybrown-dark /usr/share/icons/Yaru-yellow /usr/share/icons/Yaru-yellow-dark
fi
# End automatically added section
